### PR TITLE
Create blank.yml

### PR DESCRIPTION
**Pull request by abbaskiko**

### CODE REVIEW

**Comment by abbaskiko** [comment]
done to work

**Comment by abbaskiko** [comment]
work done sucessfull

**Comment by ehildenb** [comment]
Note sure what this PR is, but we don't use GitHub actions, we use Jenkins. Closing, re-open if this was intended.

**Comment by abbaskiko** [comment]
i use jenkins with githubs linked why you say that?
if you take a look before close it you can see my working on jenkins too

**Pull request closed without merging**
