### PR TITLE
Clean kevm branch with just one commit

### PR DESCRIPTION
**Pull request by denis-bogdanas**

### CODE REVIEW

**Comment by daejunpark** [comment]
not found: https://github.com/kframework/evm-semantics/c2b48f99bb8e3a0d54a34521457b86d893eb53a4

**Comment by daejunpark** [comment]
you can even delete the last commit you made in K: https://github.com/kframework/evm-semantics/commit/c2b48f99bb8e3a0d54a34521457b86d893eb53a4

since .k.rev file already refers to: be708fe8ea35de3b4d54d21780548fc12b2faf20

**Comment by daejunpark** [comment]
but if you want/need to keep the k submodule update in the kevm repo, then feel free to merge, once tests pass.

**Comment by denis-bogdanas** [comment]
Right. Updated kevm.rev to master.

**Pull request merged**
