### PR TITLE
License under The Reproducibility License 1.1.0

### PR DESCRIPTION
**Pull request by kemitchell**
cc @pmackay1982 and @daejunpark 

This pull request adds a public license to the repository, which it did not have before. It also adds a new section to README mentioning that licensing, linking directly to the most important section of its text, and noting that other parts of the tool chain are and remain open source, under their respective licenses.

### CODE REVIEW

**Comment by daejunpark** [comment]
@kemitchell Does this term allows others to produce a new result based on ours for the "non-commercial" purpose?

**Comment by kemitchell** [comment]
@pmackay1982 and @daejunpark, I've updated this PR with the latest license text.

**Comment by dazzaji** [comment]
Any idea where this license originate from?  It's very interesting and I might want to use it for some projects that are intended to be reproducible.  Thanks.

**Comment by kemitchell** [comment]
@dazzaji drop me a line at kyle@kemitchell.com.

**Pull request merged**
