### PR TITLE
Gnosis-bmc-pr

### PR DESCRIPTION
**Pull request by anvacaru**
**What**
1. Tweaked `checkSignatures-thres-1-sig-v0`:
     - replaced the old signature with a valid one
     - added a macro for the account id named `new_acct_id`
2. Added a local abstract-semantics.k file without the rule for `extCodeSize`

### CODE REVIEW

**Comment by daejunpark** [comment]
i stopped the jenkins build, because the top-level makefile doesn't test this anyway.  please rebase on the latest master.

**Comment by daejunpark** [comment]
@anvacaru the last commit makes the jenkins test running more than 5 hours, overwhelming the jenkins server.  did you check if the checkSignatures-thres-1-sig-v0 spec works in your local machine?

**Comment by daejunpark** [comment]
to simulate the jenkins environment, you have to run:
```
$ cd gnosis/bmc
$ make clean-deps
$ make split-proof-test
$ make /absolute/path/to/checkSignatures-thres-1-sig-v0.spec.k.test
```

**Comment by anvacaru** [comment]
> @anvacaru the last commit makes the jenkins test running more than 5 hours, overwhelming the jenkins server. did you check if the checkSignatures-thres-1-sig-v0 spec works in your local machine?

Yes, I've tested it locally before the push and there were no issues. Today I ran it again using 
```$ cd gnosis/bmc
$ make clean-deps
$ make all
$ make /absolute/path/to/checkSignatures-thres-1-sig-v0.spec.k.test
```
and it proved successfully.
```
==================================

#True

SPEC PROVED: /mnt/c/home/verified-smart-contracts/specs/gnosis-bmc/checkSignatures-thres-1-sig-v0-spec.k Location(11,5,220,17)
==================================
Execution paths: 1
Longest path: 15971 steps
Total time:            797.392
  Parsing time:        54.993
  Initialization time: 24.164
  Execution time:      718.235

Init+Execution time:    742.399
  query build time:     3.505 s
  Z3 Regular rule implication  time:  0.037 s
    executed queries:     1
      unsat (proved):       1
  Z3 Function rule implication time:  0.506 s
    executed queries:     16
      sat           :       13
      unsat (proved):       3
    cached queries:       3484
    query build failures: 656
  Z3 Regular rule constraint   time:  0.140 s
    executed queries:     4
      sat           :       2
      unsat (proved):       2
  Z3 Spec rule constraint      time:  95.911 s
    executed queries:     2975
      sat           :       2975
    timeouts:             4
  resolveFunction time: 259.121 s
Used memory:                   5235 MB

resolveFunction top-level uncached: 939807
resolveFunction top-level cached:   251056171
resolveFunction recursive uncached: 343959

impliesSMT time:    1.066 s
impliesSMT count: 5121
==================================

[Warning] Critical: execution phase: missing SMTLib translation for
#callFailure (missing SMTLib translation for #callFailure)
[Warning] Critical: execution phase: missing SMTLib translation for
#callSuccess (missing SMTLib translation for #callSuccess)
[Warning] Critical: execution phase: missing SMTLib translation for #isBuf
(missing SMTLib translation for #isBuf)
[Warning] Critical: execution phase: missing SMTLib translation for #symCmem
(missing SMTLib translation for #symCmem)
[Warning] Critical: execution phase: missing SMTLib translation for Cgascap
(missing SMTLib translation for Cgascap)
```

**Comment by denis-bogdanas** [comment]
Our colleagues on Slack were writing that Jenkins was taking all 80 GB of memory. One single test takes only 6 GB of heap. Sure there aren't multiple tests with the problem?

**Comment by denis-bogdanas** [comment]
I'm going to re-enable the project to test my PRs. If you push something, please monitor Jenkins progress and announce your collagues if you see problems.

**Pull request closed without merging**
