### PR TITLE
[WIP] Spec addToken

### PR DESCRIPTION
**Pull request by nrryuya**
success
```
AssertionError while matching subject:
========================

#unparseByteStackAux(#padToWidth(Int(#"20"),, #asByteStack(ACCT_ID:Int)),, String(#""""))

 to pattern:
------------------------
R_STR_901:String
java.lang.AssertionError: unexpected class at matching: class org.kframework.backend.java.kil.KList
    at org.kframework.backend.java.symbolic.FastRuleMatcher.match(FastRuleMatcher.java:369)
    at org.kframework.backend.java.symbolic.FastRuleMatcher.matchAndLog(FastRuleMatcher.java:227)
    at org.kframework.backend.java.symbolic.FastRuleMatcher.unifyEquality(FastRuleMatcher.java:190)

略

    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:118)
    at org.kframework.main.Main.runApplication(Main.java:107)
    at org.kframework.main.Main.main(Main.java:53)
```

Failure
```
[Error] Critical: Function evaluation triggered infinite recursion. Trace:
(null)
  while evaluating function keccak
  while evaluating function keccakIntList
  while evaluating function keccak
  while evaluating function keccakIntList
  while evaluating function keccak

略
```

### CODE REVIEW

**Comment by nrryuya** [comment]
@rv-jenkins 
I'm so sorry. This was a mistake. I intended to make pull request to our forked repo.

**Comment by daejunpark** [comment]
Hi @nrryuya, great to see that someone uses our verification tool, and hope it works for you! Just out of curiosity, is the name `plasma` related to the Ethereum Plasma project (https://plasma.io/) by any chance?

**Comment by nrryuya** [comment]
Hi @daejunpark !
My team is interested in K and happy to use it.
Yeah absolutely we are working on the formal verification of Etherreum Plasma's root chain contracts (specifically OmiseGo's MVP-based Plasma https://github.com/omisego/plasma-contracts).
We have just started so not familiar with KEVM though...

**Comment by pmackay1982** [comment]
@nrryuya - any chance you or folks from your team will be at DevCon in Prague at the end of the month? If yes, we’d love to find some time to meet. - Patrick, Runtime

**Comment by nrryuya** [comment]
@pmackay1982 
I really want to talk with you!
About devcon, I can go 70%(ticket is uncertain)...

**Comment by nrryuya** [comment]
BTW, is there any way to do debugging (to solve something like the above)?

**Pull request closed without merging**
