### PR TITLE
Vote rebased: proc_reward, vote failure cases, a few vote success cases.

### PR DESCRIPTION
**Pull request by denis-bogdanas**
Contains the following:
1. proc_reward - all 8 success execution paths in 1 spec.
2. vote - all failure execution paths in 10 specs, full coverage.
3. vote success - 2 spec that cover 3 execution paths, produced by first 2 if statements. Each spec covers a separate case generated by shift operator, in addition to branching produced by if statements.

All verified to pass before the rebase, one run after the rebase. Rebase was pretty safe, all should pass here as well. All verified on `casper_custom_logs` that includes eliminating states that include contradiction in PC.

### CODE REVIEW

**Comment by denis-bogdanas** [comment]
@daejunpark Can you merge please?

**Comment by shd101wyy** [comment]
Jenkins: test this please

**Comment by shd101wyy** [comment]
Jenkins: test this please

**Comment by shd101wyy** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
by #28

**Pull request closed without merging**
