### PR TITLE
Vote rebased clean

### PR DESCRIPTION
**Pull request by denis-bogdanas**
rebased one more time.

### CODE REVIEW

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Comment by denis-bogdanas** [comment]
Strange error message:
Unable to checkout '177cfde291d9d260cf5b430830ee8a9b258a9224' in submodule path '.build/evm-semantics'

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Comment by daejunpark** [comment]
jenkins: test this please

**Comment by daejunpark** [comment]
jenkins: test this please

**Comment by daejunpark** [comment]
jenkins: test this please

**Comment by shd101wyy** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
@denis-bogdanas the reason is because the evm-semantics submodule commit is not availalbe in the evm-semantics repo. I pushed the commit, and it should work. But right now, I cannot trigger the jenkins. It doesn't work.

**Comment by daejunpark** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
Jenkins: retest this please

**Comment by denis-bogdanas** [comment]
Related to submodule commit: that's strange. I could checkout that local commit on my machine. Now some test is failing. Will investigate that.

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Comment by daejunpark** [comment]
Regarding the submodule issue, in you local machine, you may have a legacy snapshot that doesn't exist in the remote repo any more.

Regarding the test failure, could you try to revert the commit of disabling z3 mbqi option? https://github.com/kframework/k/commit/ce8e859958eea1ee324357e31895a08540283b7d

**Comment by daejunpark** [comment]
@denis-bogdanas Just to make sure, when you try to revert the commit, do not rebase but just git revert it on the top of the casper_log_rebase_2 branch. The gnosis branch still needs to use the commit snapshot.

**Comment by denis-bogdanas** [comment]
Last time Jenkins timed out after 3 hours. But about ~140 specs passed. `vote-success` alone takes 1.5 hours to finish. I increased timeout to 4 hours and commented all specs except casper and gnosis.

**Comment by daejunpark** [comment]
@denis-bogdanas It seems to pass all the casper + gnosis test within 3 hours. I triggered the whole test with increasing the time limit to 5 hours. Once this passes, I'll merge this.

**Comment by denis-bogdanas** [comment]
@daejunpark The test that fails now is `collective_reward-success-normal-2-spec.k Location(214,5,353,42)`. It passed in previous run. Same happened with another test related to `collective_reward`, related to my messages on Slack. These are spurious failures.

**Comment by denis-bogdanas** [comment]
@daejunpark P.S. Flaky failures might be related to z3 running in highly concurrent environment. It probably proves final implication in some cases but fails to do so in other cases. When there are multiple tasks run in parallel on same machine, z3 has higher chance to timeout. This is probably related to your z3 settings changes.

Btw you did run a number of benchmarks. Did you get any performance improvements?

**Comment by denis-bogdanas** [comment]
2 tests failed this time, but they both passed earlier. Looks like restoring old z3 settings had no effect.

**Comment by daejunpark** [comment]
The original commit 9437a94 is merged into master.

**Pull request closed without merging**
